bin: Add SNMP test script

diff --git a/bin/.local/scripts/snmptesting b/bin/.local/scripts/snmptesting
--- a/bin/.local/scripts/snmptesting
+++ b/bin/.local/scripts/snmptesting
@@ -5,21 +5,37 @@
 
 # snmpwalk throw errors on internal and Wimark OID/ MIBs
 # sudo apt install snmp-mibs-downloader
+#
+# MIB structure
+# https://blog.paessler.com/snmp-deep-dive-how-smi-contributes-to-snmp
 
 
-# Warning: change this values for your needs
-COMMINITY="public"      # comminity string
-IPADDR="192.168.0.100"  # AP IP address
 
+AGENT=""  # SNMP Agent IPADDR (located on AP)
+DIRLIST="+$(pwd)/mibs" # Add '+' so default SNMP MIBs used too
+MIBLIST="WIMARK-ID-REC-MIB:CPE-SYSTEM-MIB:CPE-WIRELESS-MIB:CPE-DEMO-MIB"
+COMMINITY="public"  # comminity string
+OPT_COMM="-Cp"      # print the number of variables found
+OPT_OUTPUT="-Oa" # show ASCII
+PROGNAME="snmptesting"
 
 
 function usage() {
     cat << EOF
+Usage: $PROGNAME [OPTIONS] AGENT [[MODULE] [COMMAND]]
+
+Notes:
+    AGENT       - SNMP Agent IPADDR (located on AP)
+    COMMAND     - there's only one command for now: check. See below
+    MODULE      - what part of OID tree to get (default whole tree)
+
+MODULES:
+    system      - Show system objects
+    cpe         - Show cpe objects  (Wimark Systems extension)
+    wireless    - Show wifi objects (Wimark Systems extension)
+
 COMMANDS:
     check       - Check SNMP agent is up and running
-    system      - Show system OID range values
-    cpe         - Show cpe OID range values
-    wireless    - Show wifi OID range values
 
 OPTIONS:
     -n          - Displays the OID numerically
@@ -27,62 +43,69 @@ OPTIONS:
 EOF
 }
 
-OPT_OUTPUT="-Oa" # show ASCII
-while getopts ":nhv" opt; do
-    case "$opt" in
-        n)
-            OPT_OUTPUT="-On" # show numeric
-            ;;
-        h)
-            usage
-            exit 0
-            ;;
-        v)
-            OPT_OUTPUT="-Ov" # show ASCII
-            ;;
-    esac
-done
-shift $(( OPTIND - 1 ))
+function parse_args()
+{
+    while getopts ":nh" opt; do
+        case "$opt" in
+            n)
+                OPT_OUTPUT="-On" # show numeric
+                ;;
+            h)
+                usage
+                exit 0
+                ;;
+            *)
+                echo "error: no such option '-$OPTARG'"
+                exit 1
+        esac
+    done
 
-# Options
-OPT_COMM="-Cp"   # print the number of variables found
-OPTS="${OPT_OUTPUT} ${OPT_COMM} -v 2c"
+    shift $(( OPTIND - 1 ))
+    AGENT="$1"
+    MODULE="$2"
 
-# Values
-CPE_OID_RANGE=".1.3.6.1.4.1.52400.2.1"
-WIFI_OID_RANGE=".1.3.6.1.4.1.52400.2.3"
-OPT_LIST="CPE-SYSTEM-MIB:CPE-WIRELESS-MIB:WIMARK-ID-REC-MIB"
+    if [ -z "$AGENT" ]; then
+        echo "error: AGENT missing. Use 'snmptesting -h' to get help."
+        exit 1
+    fi
 
-# Form a complete command
-SNMPCMD="snmpwalk $OPTS -c $COMMINITY -v 1 -m $OPT_LIST $IPADDR"
+    check_module $MODULE
 
+    # Form a complete SNMPWalk command
+    OPTS="${OPT_OUTPUT} ${OPT_COMM} -v 1"
+    SNMPCMD="snmpwalk $OPTS -c $COMMINITY -m $MIBLIST -M $DIRLIST $AGENT"
+}
 
+function check_module()
+{
+    local argmod="$1"
+    local modules=(check cpe wireless system)
 
+    # no module specified, traverse a whole OID tree
+    if [[ -z "$argmod" ]]; then
+        MODULE="."
+        return
+    fi
 
+    for module in ${modules[@]}; do
+        if [[ "$module" == "$argmod" ]]; then
+            return
+        fi
+    done
+
+    echo "error: no such module '$argmod'. Use 'snmptesting -h' to get help."
+    exit 0
+}
 
 function main()
 {
-    # default: list all range OID
-    if [ -z "$1" ]; then
-        $SNMPCMD .
-    elif [ "$1" = "check" ]; then
-        snmp-check -v2c -c $COMMINITY $IPADDR
-        # roachme:
-        # 1. Set timeout value when tryng to connect to SNMP daemon
-        # 2. Output status depending on command above
-        #echo "Status: SNMP daemon is up and running on target $IPADDR"
+    parse_args $@
 
-    elif [ "$1" = "system" ]; then
-        $SNMPCMD system
-    elif [ "$1" = "cpe" ]; then
-        $SNMPCMD cpe
-    elif [ "$1" = "wireless" ]; then
-        $SNMPCMD wireless
+    if [ "$MODULE" = "check" ]; then
+        snmp-check -v2c -c $COMMINITY $AGENT
     else
-        usage
+        $SNMPCMD $MODULE
     fi
 }
 
 main $@
-
-#snmpwalk -v 2c -c public -v 1 -m CPE-SYSTEM-MIB:CPE-WIRELESS-MIB:WIMARK-ID-REC-MIB 192.168.0.100 .
